-- TIPOS / CATEGORÍAS DE PRODUCTO (puede ser jerárquico si luego agregás parent_id)
CREATE TABLE IF NOT EXISTS product_type (
                                            id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            name      VARCHAR(120) NOT NULL,
    slug      VARCHAR(160) UNIQUE,
    description TEXT
    );

-- PRODUCTO (SPU: la ficha general que ve el usuario)
CREATE TABLE IF NOT EXISTS product (
                                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       type_id     BIGINT NOT NULL,
                                       name        VARCHAR(180) NOT NULL,
    slug        VARCHAR(200) UNIQUE,
    short_desc  VARCHAR(300),
    description TEXT,
    is_active   BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_product_type FOREIGN KEY (type_id) REFERENCES product_type(id)
    );

-- VARIANTE (SKU: unidad vendible con precio y stock simples de arranque)
CREATE TABLE IF NOT EXISTS product_variant (
                                               id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               product_id   BIGINT NOT NULL,
                                               sku          VARCHAR(64) UNIQUE NOT NULL,
    title        VARCHAR(180),                 -- ej: "10\" • 5µm", "15kg", "17x7.5"
    price        NUMERIC(12,2) NOT NULL,
    stock        INT NOT NULL DEFAULT 0,
    is_active    BOOLEAN DEFAULT TRUE,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT fk_variant_product FOREIGN KEY (product_id) REFERENCES product(id)
    );

-- IMÁGENES (a nivel producto o variante)
CREATE TABLE IF NOT EXISTS product_image (
                                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             product_id  BIGINT,
                                             variant_id  BIGINT,
                                             url         VARCHAR(255) NOT NULL,
    alt_text    VARCHAR(160),
    sort_order  INT DEFAULT 0,
    CONSTRAINT fk_img_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_img_variant FOREIGN KEY (variant_id) REFERENCES product_variant(id)
    );

-- ÍNDICES útiles
CREATE INDEX IF NOT EXISTS idx_product_type    ON product(type_id);
CREATE INDEX IF NOT EXISTS idx_product_slug    ON product(slug);
CREATE INDEX IF NOT EXISTS idx_variant_sku     ON product_variant(sku);
CREATE INDEX IF NOT EXISTS idx_image_product   ON product_image(product_id);
CREATE INDEX IF NOT EXISTS idx_image_variant   ON product_image(variant_id);
