-- V3__create_app_user.sql
-- Crea tabla de usuarios de la app y siembra un ADMIN inicial.

CREATE TABLE IF NOT EXISTS app_user (
                                        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        email          VARCHAR(160) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(20)  NOT NULL,  -- 'ADMIN' o 'CLIENT'
    full_name      VARCHAR(160),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- Admin inicial: santiagobarrionuevo9@gmail.com / GaveAdmin#2025
INSERT INTO app_user (email, password_hash, role, full_name)
VALUES (
           'santiagobarrionuevo9@gmail.com',
           '$2b$10$lErtb7DSLNEiZMT0SL6Fo.yHk2D3c1FkVYV0d8HBPrGT59ihkTaBK',
           'ADMIN',
           'Administrador'
       )
    ON CONFLICT (email) DO NOTHING;
