-- método de entrega y costos
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_method VARCHAR(32) NOT NULL DEFAULT 'DELIVERY';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_cost NUMERIC(12,2) NOT NULL DEFAULT 0;

-- dirección embebida
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_street      VARCHAR(180);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_number      VARCHAR(30);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_apt         VARCHAR(80);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_reference   VARCHAR(200);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_city        VARCHAR(120);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_province    VARCHAR(120);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_postal_code VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_lat         DOUBLE PRECISION;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_lng         DOUBLE PRECISION;
